name: Validate ECR Address from docker file
on:
  pull_request:
    branches: ["*"]
      
  repository_dispatch:
    types: [org-workflow-bot]  
jobs:
  register:
    runs-on: ubuntu-latest
    steps:
    - uses: SvanBoxel/organization-workflow@main
      with:
        id: ${{ github.event.client_payload.id }}
        callback_url: ${{ github.event.client_payload.callback_url }}
        sha: ${{ github.event.client_payload.sha }}
        run_id: ${{ github.run_id }}
        name: ${{ github.workflow }}
        enforce: true
        documentation: "ony-org.sh"
  main:
    needs: [register]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Self Repository
      uses: actions/checkout@v2.3.4
    - uses: actions/cache@v2
      with:
      path: scripts/ony-org.sh
      key: ${{ runner.os }}-Dockerfile-${{ hashFiles('**/*.sh*') }}
      restore-keys: ${{ runner.os }}-Dockerfile-
    - name: Checkout Member Repository
      uses: actions/checkout@v2.3.4
      with:
        repository: ${{ github.event.client_payload.repository.full_name }}
        ref: ${{ github.event.client_payload.sha }}
        token: ${{ github.event.client_payload.token }}
    - name: Download a checker file
      uses: actions/download-artifact@v3
      with:
        name: checker-file
    # - name: list files 
    #   run: ls -laR
    - name: Validate dockerfile base address
      run: bash -x ecr-address-checker.sh
      
 