name: Validate ECR Address from docker file
on: [push]

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Validate dockerfile base address
      run: bash -x ony-org.sh
