name: Validate ECR Address from Dockerfile
on:
  pull_request:
    branches: ["*"]
      
  repository_dispatch:
    types: [org-workflow-bot]  

jobs:
  register:
    runs-on: ubuntu-latest
    steps:
    - uses: SvanBoxel/organization-workflow@main
      with:
        id: ${{ github.event.client_payload.id }}
        callback_url: ${{ github.event.client_payload.callback_url }}
        sha: ${{ github.event.client_payload.sha }}
        run_id: ${{ github.run_id }}
        name: ${{ github.workflow }}
        enforce: true
        documentation: ".github/workflows/ECR-Addr-Check.md"

  main:
    needs: [register]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Self
      uses: actions/checkout@v2.3.4
    - shell: bash
      run: |
        cp ony-org.sh ecr-address-checker.sh
    - name: Upload checker file
      uses: actions/upload-artifact@v3
      with:
        name: checker-file
        path: ecr-address-checker.sh
    - name: Checkout Member
      uses: actions/checkout@v2.3.4
      with:
        repository: ${{ github.event.client_payload.repository.full_name }}
        ref: ${{ github.event.client_payload.sha }}
        token: ${{ github.event.client_payload.token }}
    - name: Download checker file
      uses: actions/download-artifact@v3
      with:
        name: checker-file
    - name: Validate dockerfile base ECR address
      run: bash -x ecr-address-checker.sh
