name: Validate ECR Address from docker file
# on: [push]
# on:
on:
  pull_request:
    branches:
      - main
  repository_dispatch:
    types: [org-workflow-bot]  
   
jobs:
  register:
    runs-on: ubuntu-latest
    steps:
    - uses: SvanBoxel/organization-workflow@main
      with:
        id: ${{ github.event.client_payload.id }}
        callback_url: ${{ github.event.client_payload.callback_url }}
        sha: ${{ github.event.client_payload.sha }}
        run_id: ${{ github.run_id }}
        name: ${{ github.workflow }}
        enforce: true
        documentation: Using Incorrect ECR address
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        repository: ${{ github.event.client_payload.repository.full_name }}
        ref: ${{ github.event.client_payload.sha }}
        token: ${{ github.event.client_payload.token }}

  main:
    needs: [register]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Validate dockerfile base address
      run: bash -x ony-org.sh
